$show_time = 1;
$dependents_phony = 1;
$do_cd = 1;
$preview_continuous_mode = 1;
@default_files = ('*.tex', '*.ins', '*.dtx');
$clean_ext = 'synctex(busy) synctex.gz acn acr alg aux bbl bcf blg brf hd \
fdb_latexmk glg glo gls idx ilg ind ist loe lof log lot out run.xml toc xdv dvi \
upa upb pygtex pygstyle pyg fls listing cmap csvtoken gnuplot nav snm vrb mw \
mw.mw fmt markdown.in nlo nls md5 dpth auxlock figlist';
$clean_full_ext = 'sty cls';

$pdf_mode = 5;
$xelatex = 'xelatex -shell-escape -file-line-error -halt-on-error \
-interaction=nonstopmode -no-pdf -synctex=1 %O %S';

$pdf_previewer = 'xdg-open %S';
$makeindex = 'makeindex -s gind.ist %O -o %D %S';
$compiling_cmd = 'xdotool search --name "%D" set_window --name "%D "';
$success_cmd   = 'xdotool search --name "%D" set_window --name "%D ✔"';
$failure_cmd   = 'xdotool search --name "%D" set_window --name "%D ✗"';
$warning_cmd   = 'xdotool search --name "%D" set_window --name "%D ⚠"';

add_cus_dep('nlo', 'nls', 0, 'nlo2nls');
push @generated_exts, 'nlo', 'nls';
sub nlo2nls{
	system('makeindex -s nomencl.ist -o "$_[0].nls" "$_[0].nlo"');
}
# ex: filetype=perl
