---
version: 2
updates:
  - package-ecosystem: github-actions
    target-branch: dev
    directory: /
    schedule:
      interval: monthly
  - package-ecosystem: gitsubmodule
    target-branch: dev
    directory: /
    schedule:
      interval: monthly
