{{ join(readfile(expand('~/.config/nvim/templates/%.nvim/.github/workflows/main.yml')), "\n") }}

  test:
    needs: build
    strategy:
      fail-fast: false
      matrix:
        runs-on:
          - ubuntu-latest
          - macos-latest
          - windows-latest
        neovim:
          - true
          - false
    runs-on: ${{matrix.runs-on}}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/checkout@v4
        with:
          repository: thinca/vim-themis
          path: vim-themis
      - uses: rhysd/action-setup-vim@v1
        id: vim
        with:
          neovim: ${{matrix.neovim}}
      - name: Run unit tests with themis.vim
        run: |
          vim-themis/bin/themis
        env:
          THEMIS_VIM: ${{steps.vim.outputs.executable}}
