version = 1
exclude_patterns = []
# https://github.com/deepsourcelabs/cli/issues/198
test_patterns = ["tests/*_test.py", "tests/test_*.py"]

[[analyzers]]
name = "docker"
enabled = true

[[analyzers]]
name = "python"
enabled = true

[[analyzers]]
name = "shell"
enabled = true

[analyzers.meta]
dockerfile_paths = ".docker/Dockerfile"

[[transformers]]
name = "black"
enabled = true
