# suid will chown root:root
sys-apps/util-linux -suid
# libtiff use webp will result in recursive dependence
media-libs/libwebp -tiff
# rime-emoji
app-i18n/rime-data extra
# neovim
dev-libs/libutf8proc -cjk
