# https://docs.readthedocs.io/en/stable/config-file/v2.html
---
version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3"
  commands:
    - asdf plugin add lua
    - asdf install lua 5.1
    # full path can declare lua version
    - ~/.asdf/installs/lua/5.1/luarocks/bin/luarocks install ldoc
    - ~/.asdf/installs/lua/5.1/luarocks/bin/ldoc .
