---
"on":
  push:
    paths-ignore:
      - "**.md"
      - docs/*
  pull_request:
    paths-ignore:
      - "**.md"
      - docs/*
  workflow_dispatch:

# https://github.com/softprops/action-gh-release/issues/236
permissions:
  contents: write

env:
  files: dist/*

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        runs-on:
          - ubuntu-latest
          - macos-latest
          - windows-latest
    runs-on: ${{matrix.runs-on}}
    steps:
      - uses: actions/checkout@v4
      - uses: astral-sh/setup-uv@v6
      - name: Install dependencies
        run: |
          uv pip install -e '.[dev]'
      - name: Test
        run: |
          pytest --cov
      - uses: codecov/codecov-action@v4

  build:
    needs: test
    strategy:
      fail-fast: false
      matrix:
        runs-on:
          - ubuntu-latest
          - macos-latest
          - windows-latest
    runs-on: ${{matrix.runs-on}}
    steps:
      - uses: actions/checkout@v4
      - uses: astral-sh/setup-uv@v6
      - name: Build
        run: |
          uv build
      - uses: pypa/gh-action-pypi-publish@release/v1
        if: runner.os == 'Linux' && startsWith(github.ref, 'refs/tags/')
        with:
          password: ${{secrets.PYPI_API_TOKEN}}
      - uses: actions/upload-artifact@v4
        if: "! startsWith(github.ref, 'refs/tags/')"
        with:
          name: artifact-${{matrix.runs-on}}
          path: |
            ${{env.files}}
      - uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          # body_path: build/CHANGELOG.md
          files: |
            ${{env.files}}

  deploy-aur:
    needs: build
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/')
    steps:
      - uses: Freed-Wu/update-aur-package@v1.0.11
        with:
          package_name: python-{{ expand('%:p:h:h:h:t') }}
          ssh_private_key: ${{secrets.AUR_SSH_PRIVATE_KEY}}

  deploy-nur:
    needs: build
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/')
    steps:
      - name: Trigger Workflow
        run: >
          curl -X POST -d '{"ref": "main"}'
          -H "Accept: application/vnd.github.v3+json"
          -H "Authorization: Bearer ${{secrets.GH_TOKEN}}"
          https://api.github.com/repos/Freed-Wu/nur-packages/actions/workflows/version.yml/dispatches

  deploy-ppa:
    needs: build
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/')
    steps:
      - uses: actions/checkout@v4
        with:
          path: {{ expand('%:p:h:h:h:t') }}-${{github.ref_name}}
      - name: Build
        run: |
          tar vcaf {{ expand('%:p:h:h:h:t') }}-${{github.ref_name}}.tar.gz {{ expand('%:p:h:h:h:t') }}-${{github.ref_name}}
      - uses: yuezk/publish-ppa-package@main
        with:
          repository: freedwu/ppa
          gpg_private_key: ${{secrets.GPG_PRIVATE_KEY}}
          gpg_passphrase: ${{secrets.GPG_PASSPHRASE}}
          tarball: ./*.tar.*
          deb_email: ${{secrets.DEB_EMAIL}}
          deb_fullname: freedwu
          debmake_arguments: -mb{{ expand('%:p:h:h:h:t') }}:python3
