---
"on":
  push:
    paths-ignore:
      - "**.md"
  pull_request:
    paths-ignore:
      - "**.md"
  workflow_dispatch:

# https://github.com/softprops/action-gh-release/issues/236
permissions:
  contents: write

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        runs-on:
          - ubuntu-latest
          - macos-latest
    runs-on: ${{matrix.runs-on}}
    steps:
      - uses: actions/checkout@v4
      - uses: shogo82148/actions-setup-perl@v1
      - name: Install Dependencies
        run: >
          cpanm -qn Dist::Zilla::App::Command::cover
          Devel::Cover::Report::Codecovbash
      - name: Test
        run: |
          git config github.user "$GITHUB_REPOSITORY_OWNER"
          dzil authordeps --missing | cpanm -qn
          dzil cover -test -report codecovbash
      - uses: codecov/codecov-action@v3

  build:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - uses: actions/checkout@v4
      - uses: shogo82148/actions-setup-perl@v1
      - name: Install Dependencies
        run: |
          cpanm -qn Dist::Zilla CPAN::Uploader
      - name: Build
        run: |
          git config github.user "$GITHUB_REPOSITORY_OWNER"
          dzil authordeps --missing | cpanm -qn
          dzil build
          perl -0777 -ni -e'/## .*?\n\n(.*?)\n\n\n/s; print $1' CHANGELOG.md
      - name: Upload
        if: startsWith(github.ref, 'refs/tags/')
        run: >
          cpan-upload -u ${{secrets.CPAN_USERNAME}}
          -p ${{secrets.CPAN_PASSWORD}} ./*.tar.gz
      - uses: actions/upload-artifact@v3
        if: "! startsWith(github.ref, 'refs/tags/')"
        with:
          path: |
            *.tar.gz
      - uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          body_path: CHANGELOG.md
          files: |
            *.tar.gz

  deploy-aur:
    needs: build
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/')
    steps:
      - uses: Freed-Wu/update-aur-package@v1.0.11
        with:
          package_name: perl-{{ tolower(expand('%:p:h:h:h:t')) }}
          ssh_private_key: ${{secrets.AUR_SSH_PRIVATE_KEY}}

  deploy-nur:
    needs: build
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/')
    steps:
      - name: Trigger Workflow
        run: >
          curl -X POST -d '{"ref": "main"}'
          -H "Accept: application/vnd.github.v3+json"
          -H "Authorization: Bearer ${{secrets.GH_TOKEN}}"
          https://api.github.com/repos/Freed-Wu/nur-packages/actions/workflows/version.yml/dispatches

  deploy-ppa:
    needs: build
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/')
    steps:
      - uses: actions/checkout@v4
        with:
          path: {{ expand('%:p:h:h:h:t') }}-${{github.ref_name}}
      - name: Build
        run: |
          tar vcaf {{ expand('%:p:h:h:h:t') }}-${{github.ref_name}}.tar.gz {{ expand('%:p:h:h:h:t') }}-${{github.ref_name}}
      - uses: yuezk/publish-ppa-package@main
        with:
          repository: freedwu/ppa
          gpg_private_key: ${{secrets.GPG_PRIVATE_KEY}}
          gpg_passphrase: ${{secrets.GPG_PASSPHRASE}}
          tarball: ./*.tar.*
          deb_email: ${{secrets.DEB_EMAIL}}
          deb_fullname: freedwu
          debmake_arguments: -mb{{ expand('%:p:h:h:h:t') }}:perl
