---
"on":
  push:
    paths-ignore:
      - "**.md"
  pull_request:
    paths-ignore:
      - "**.md"
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: mig4/setup-bats@v1
      # https://github.com/mig4/setup-bats/issues/67
      - uses: brokenpip3/setup-bats-libs@0.1.0
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: "3.0"
          bundler-cache: true
      - name: Install Ruby dependencies
        run: |
          bundle update --bundler && bundle install
      # https://github.com/Freed-Wu/hhighlighter-rg/actions/runs/3450224257/jobs/5758684620#step:8:5
      - name: Test
        run: |
          TMPDIR=/tmp bundle exec bashcov -- bats -r .
      - uses: codecov/codecov-action@v3
        with:
          files: coverage/codecov-result.json
