---
"on":
  push:
  pull_request:
  workflow_dispatch:

env:
  path: "*.pdf"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: xu-cheng/latex-action@v2
        with:
          root_file: |
            *.tex
          glob_root_file: true
          latexmk_use_xelatex: true
      - uses: actions/upload-artifact@v3
        if: ${{ ! startsWith(github.ref, 'refs/tags/') }}
        with:
          path: |
            ${{ env.path }}
      - uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            ${{ env.path }}
