---
"on":
  push:
    paths-ignore:
      - "**.md"
  pull_request:
    paths-ignore:
      - "**.md"
  workflow_dispatch:

# https://github.com/softprops/action-gh-release/issues/236
permissions:
  contents: write

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        runs-on:
          - ubuntu-latest
          - macos-latest
    runs-on: ${{matrix.runs-on}}
    steps:
      - uses: actions/checkout@v3
      - uses: shogo82148/actions-setup-perl@v1
      - name: Install Dependencies
        run: >
          cpanm -qn Dist::Zilla::App::Command::cover
          Devel::Cover::Report::Codecovbash
      - name: Test
        run: |
          git config github.user $GITHUB_REPOSITORY_OWNER
          dzil authordeps --missing | cpanm -qn
          dzil cover -test -report codecovbash
      - uses: codecov/codecov-action@v3

  deploy:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - uses: actions/checkout@v3
      - uses: shogo82148/actions-setup-perl@v1
      - name: Install Dependencies
        run: |
          cpanm -qn Dist::Zilla CPAN::Uploader
          sudo apt-get -y update
          sudo apt-get -y install po4a
      - name: Build
        run: |
          po4a po4a/po4a.cfg
          git config github.user $GITHUB_REPOSITORY_OWNER
          dzil authordeps --missing | cpanm -qn
          dzil build
          perl -0777 -ni -e'/## .*?\n\n(.*?)\n\n\n/s; print $1' CHANGELOG.md
      - name: Upload
        if: startsWith(github.ref, 'refs/tags/')
        run: >
          cpan-upload -u ${{secrets.CPAN_USERNAME}}
          -p ${{secrets.CPAN_PASSWORD}} *.tar.gz
      - uses: actions/upload-artifact@v3
        if: "! startsWith(github.ref, 'refs/tags/')"
        with:
          path: |
            *.tar.gz
      - uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          body_path: CHANGELOG.md
          files: |
            *.tar.gz
  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: Freed-Wu/update-aur-package@v1.0.10
        if: startsWith(github.ref, 'refs/tags/')
        with:
          package_name: perl-{{ tolower(expand('%:p:h:h:h:t')) }}
          ssh_private_key: ${{secrets.AUR_SSH_PRIVATE_KEY}}
