---
Diagnostics:
  UnusedIncludes: Strict
Hover:
  ShowAKA: true
CompileFlags:
  # https://github.com/clangd/clangd/issues/662#issuecomment-1447233948
  Remove:
    - -m*
    - -f*
  Add:
    - -Wall
