---
"on":
  push:
    paths-ignore:
      - "**.md"
  pull_request:
    paths-ignore:
      - "**.md"
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: mig4/setup-bats@v1
      - uses: brokenpip3/setup-bats-libs@0.1.0
      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install check
      - name: Test
        # disable bashcov due to bug
        run: |
          bats -r .
          make check
      - uses: codecov/codecov-action@v3
        with:
          gcov: true
