---
"on":
  push:
    paths-ignore:
      - "**.md"
  pull_request:
    paths-ignore:
      - "**.md"
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install check
      - name: Test
        # https://bugs.launchpad.net/ubuntu/+source/check/+bug/2019478
        run: |
          cmake -Bbuild
          cmake --build build --target check_{{ expand('%:p:h:h:h') }}
          ctest --test-dir build
      - uses: codecov/codecov-action@v3
        with:
          gcov: true
