---
"on":
  push:
    paths-ignore:
      - "**.md"
  pull_request:
    paths-ignore:
      - "**.md"
  workflow_dispatch:

# https://github.com/softprops/action-gh-release/issues/236
permissions:
  contents: write

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        runs-on:
          - ubuntu-latest
          - macos-latest
    runs-on: $\{\{ matrix.runs-on \}\}
    steps:
      - uses: actions/checkout@v3
      - uses: shogo82148/actions-setup-perl@v1
      - name: Install
        run: |
          ./Makefile.PL
          make manifest
          make install
      - name: Install Requirements
        if: startsWith(github.ref, 'refs/tags/')
        run: |
          cpanm -qn Devel::Cover Devel::Cover::Report::Codecovbash
      - name: Test
        run: |
          make test
          cover -test -report codecovbash
      - uses: codecov/codecov-action@v3

  deploy:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - uses: actions/checkout@v3
      - uses: shogo82148/actions-setup-perl@v1
      - name: Build
        run: |
          ./Makefile.PL
          make manifest
          make dist
      - uses: actions/upload-artifact@v3
        if: $\{\{ ! startsWith(github.ref, 'refs/tags/') \}\}
        with:
          path: |
            *.tar.gz
      - name: Get changelog
        if: startsWith(github.ref, 'refs/tags/')
        run: >
          mkdir -p build;
          perl -0777 -ne'/## .*?\n\n(.*?)\n\n\n/s; print $1' CHANGELOG.md >
          build/CHANGELOG.md
      - uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          body_path: build/CHANGELOG.md
          files: |
            *.tar.gz
      - name: Install Requirements
        if: startsWith(github.ref, 'refs/tags/')
        run: |
          cpanm -qn CPAN::Uploader
      - name: Upload
        if: startsWith(github.ref, 'refs/tags/')
        run: >
          cpan-upload -u $\{\{ secrets.CPAN_USERNAME \}\}
          -p $\{\{ secrets.CPAN_PASSWORD \}\} *.tar.gz
