[colors.vi_mode_cursor]
cursor = "#ff00ff"

[cursor.style]
blinking = "On"

[font]
size = 12.0

[font.normal]
family = "JetBrainsMono Nerd Font Mono"

[[keyboard.bindings]]
action = "IncreaseFontSize"
key = "Plus"
mods = "Shift|Control"

[[keyboard.bindings]]
action = "DecreaseFontSize"
key = "_"
mods = "Shift|Control"

[[keyboard.bindings]]
action = "ResetFontSize"
key = 11
mods = "Shift|Control"

[[keyboard.bindings]]
chars = ""
key = "Equals"
mods = "Control"

[[keyboard.bindings]]
chars = "\u001F"
key = "Minus"
mods = "Control"

[[keyboard.bindings]]
chars = ""
key = "Key0"
mods = "Control"

[[keyboard.bindings]]
action = "Hide"
key = "H"
mods = "Shift|Control"

[[keyboard.bindings]]
action = "CopySelection"
key = "X"
mods = "Shift|Control"

[[keyboard.bindings]]
action = "PasteSelection"
key = "P"
mods = "Shift|Control"

[[keyboard.bindings]]
chars = "\u001B[13;2u"
key = "Return"
mods = "Shift"

[[keyboard.bindings]]
chars = "\u001B[13;4u"
key = "Return"
mods = "Shift|Alt"

[[keyboard.bindings]]
chars = "\u001B[13;5u"
key = "Return"
mods = "Control"

[[keyboard.bindings]]
chars = "\u001B[13;6u"
key = "Return"
mods = "Shift|Control"

[[keyboard.bindings]]
chars = "\u001B[13;7u"
key = "Return"
mods = "Alt|Control"

[[keyboard.bindings]]
chars = "\u001B[13;8u"
key = "Return"
mods = "Shift|Alt|Control"

[selection]
save_to_clipboard = true

[window]
opacity = 0.75
# https://github.com/wez/wezterm/issues/3766
# startup_mode = "Fullscreen"
