[plugins]
"rocks.nvim" = "scm"
"rocks-config.nvim" = "scm"

nvim-treesitter = "scm"
nvim-treesitter-textobjects = "scm"
nvim-treesitter-context = "scm"

"rime.nvim" = "scm"
"ime.nvim" = "scm"

"code-stats.nvim" = "scm"

tree-sitter-ada = "scm"
tree-sitter-agda = "scm"
tree-sitter-angular = "scm"
tree-sitter-apex = "scm"
tree-sitter-arduino = "scm"
tree-sitter-asm = "scm"
tree-sitter-astro = "scm"
tree-sitter-authzed = "scm"
tree-sitter-awk = "scm"
tree-sitter-bash = "scm"
tree-sitter-bass = "scm"
tree-sitter-beancount = "scm"
tree-sitter-bibtex = "scm"
tree-sitter-bicep = "scm"
tree-sitter-bitbake = "scm"
tree-sitter-blueprint = "scm"
tree-sitter-bp = "scm"
tree-sitter-c = "scm"
tree-sitter-c_sharp = "scm"
tree-sitter-cairo = "scm"
tree-sitter-capnp = "scm"
tree-sitter-chatito = "scm"
tree-sitter-clojure = "scm"
tree-sitter-cmake = "scm"
tree-sitter-comment = "scm"
tree-sitter-commonlisp = "scm"
tree-sitter-cooklang = "scm"
tree-sitter-corn = "scm"
tree-sitter-cpon = "scm"
tree-sitter-cpp = "scm"
tree-sitter-css = "scm"
tree-sitter-csv = "scm"
tree-sitter-cuda = "scm"
tree-sitter-cue = "scm"
tree-sitter-d = "scm"
tree-sitter-dart = "scm"
tree-sitter-devicetree = "scm"
tree-sitter-dhall = "scm"
tree-sitter-diff = "scm"
tree-sitter-disassembly = "scm"
tree-sitter-djot = "scm"
tree-sitter-dockerfile = "scm"
tree-sitter-dot = "scm"
tree-sitter-doxygen = "scm"
tree-sitter-dtd = "scm"
tree-sitter-earthfile = "scm"
tree-sitter-ebnf = "scm"
tree-sitter-ecma = "scm"
tree-sitter-editorconfig = "scm"
tree-sitter-eds = "scm"
tree-sitter-eex = "scm"
tree-sitter-elixir = "scm"
tree-sitter-elm = "scm"
tree-sitter-elsa = "scm"
tree-sitter-elvish = "scm"
tree-sitter-embedded_template = "scm"
tree-sitter-erlang = "scm"
tree-sitter-facility = "scm"
tree-sitter-faust = "scm"
tree-sitter-fennel = "scm"
tree-sitter-fidl = "scm"
tree-sitter-firrtl = "scm"
tree-sitter-fish = "scm"
tree-sitter-foam = "scm"
tree-sitter-forth = "scm"
tree-sitter-fortran = "scm"
tree-sitter-fsh = "scm"
tree-sitter-func = "scm"
tree-sitter-fusion = "scm"
tree-sitter-gdscript = "scm"
tree-sitter-gdshader = "scm"
tree-sitter-git_config = "scm"
tree-sitter-git_rebase = "scm"
tree-sitter-gitattributes = "scm"
tree-sitter-gitcommit = "scm"
tree-sitter-gitignore = "scm"
tree-sitter-gleam = "scm"
tree-sitter-glimmer = "scm"
tree-sitter-glsl = "scm"
tree-sitter-gn = "scm"
tree-sitter-gnuplot = "scm"
tree-sitter-go = "scm"
tree-sitter-goctl = "scm"
tree-sitter-godot_resource = "scm"
tree-sitter-gomod = "scm"
tree-sitter-gosum = "scm"
tree-sitter-gotmpl = "scm"
tree-sitter-gowork = "scm"
tree-sitter-gpg = "scm"
tree-sitter-graphql = "scm"
tree-sitter-groovy = "scm"
tree-sitter-gstlaunch = "scm"
tree-sitter-hack = "scm"
tree-sitter-hare = "scm"
tree-sitter-haskell = "scm"
tree-sitter-haskell_persistent = "scm"
tree-sitter-hcl = "scm"
tree-sitter-heex = "scm"
tree-sitter-helm = "scm"
tree-sitter-hjson = "scm"
tree-sitter-hlsl = "scm"
tree-sitter-hlsplaylist = "scm"
tree-sitter-hocon = "scm"
tree-sitter-hoon = "scm"
tree-sitter-html = "scm"
tree-sitter-html_tags = "scm"
tree-sitter-htmldjango = "scm"
tree-sitter-http = "scm"
tree-sitter-hurl = "scm"
tree-sitter-hyprlang = "scm"
tree-sitter-idl = "scm"
tree-sitter-ini = "scm"
tree-sitter-inko = "scm"
tree-sitter-ispc = "scm"
tree-sitter-janet_simple = "scm"
tree-sitter-java = "scm"
tree-sitter-javascript = "scm"
tree-sitter-jq = "scm"
tree-sitter-jsdoc = "scm"
tree-sitter-json = "scm"
tree-sitter-json5 = "scm"
tree-sitter-jsonc = "scm"
tree-sitter-jsonnet = "scm"
tree-sitter-jsx = "scm"
tree-sitter-julia = "scm"
tree-sitter-just = "scm"
tree-sitter-kconfig = "scm"
tree-sitter-kdl = "scm"
tree-sitter-kotlin = "scm"
tree-sitter-koto = "scm"
tree-sitter-kusto = "scm"
tree-sitter-lalrpop = "scm"
tree-sitter-latex = "scm"
tree-sitter-ledger = "scm"
tree-sitter-leo = "scm"
tree-sitter-linkerscript = "scm"
tree-sitter-liquid = "scm"
tree-sitter-liquidsoap = "scm"
tree-sitter-llvm = "scm"
tree-sitter-lua = "scm"
tree-sitter-luadoc = "scm"
tree-sitter-luap = "scm"
tree-sitter-luau = "scm"
tree-sitter-m68k = "scm"
tree-sitter-make = "scm"
tree-sitter-markdown = "scm"
tree-sitter-markdown_inline = "scm"
tree-sitter-matlab = "scm"
tree-sitter-menhir = "scm"
tree-sitter-mermaid = "scm"
tree-sitter-meson = "scm"
tree-sitter-mlir = "scm"
tree-sitter-muttrc = "scm"
tree-sitter-nasm = "scm"
tree-sitter-nginx = "scm"
tree-sitter-nickel = "scm"
tree-sitter-nim = "scm"
tree-sitter-nim_format_string = "scm"
tree-sitter-ninja = "scm"
tree-sitter-nix = "scm"
tree-sitter-norg = "scm"
tree-sitter-norg-meta = "scm"
tree-sitter-nqc = "scm"
tree-sitter-objc = "scm"
tree-sitter-objdump = "scm"
tree-sitter-ocaml = "scm"
tree-sitter-ocaml_interface = "scm"
tree-sitter-ocamllex = "scm"
tree-sitter-odin = "scm"
tree-sitter-org = "scm"
tree-sitter-orgmode = "scm"
tree-sitter-pascal = "scm"
tree-sitter-passwd = "scm"
tree-sitter-pem = "scm"
tree-sitter-perl = "scm"
tree-sitter-php = "scm"
tree-sitter-php_only = "scm"
tree-sitter-phpdoc = "scm"
tree-sitter-pioasm = "scm"
tree-sitter-po = "scm"
tree-sitter-pod = "scm"
tree-sitter-poe_filter = "scm"
tree-sitter-pony = "scm"
tree-sitter-powershell = "scm"
tree-sitter-printf = "scm"
tree-sitter-prisma = "scm"
tree-sitter-problog = "scm"
tree-sitter-prolog = "scm"
tree-sitter-promql = "scm"
tree-sitter-properties = "scm"
tree-sitter-proto = "scm"
tree-sitter-prql = "scm"
tree-sitter-psv = "scm"
tree-sitter-pug = "scm"
tree-sitter-puppet = "scm"
tree-sitter-purescript = "scm"
tree-sitter-pymanifest = "scm"
tree-sitter-python = "scm"
tree-sitter-ql = "scm"
tree-sitter-qmldir = "scm"
tree-sitter-qmljs = "scm"
tree-sitter-query = "scm"
tree-sitter-r = "scm"
tree-sitter-racket = "scm"
tree-sitter-ralph = "scm"
tree-sitter-rasi = "scm"
tree-sitter-rbs = "scm"
tree-sitter-re2c = "scm"
tree-sitter-readline = "scm"
tree-sitter-regex = "scm"
tree-sitter-rego = "scm"
tree-sitter-requirements = "scm"
tree-sitter-rescript = "scm"
tree-sitter-rnoweb = "scm"
tree-sitter-robot = "scm"
tree-sitter-robots = "scm"
tree-sitter-roc = "scm"
tree-sitter-ron = "scm"
tree-sitter-rst = "scm"
tree-sitter-ruby = "scm"
tree-sitter-rust = "scm"
tree-sitter-scala = "scm"
tree-sitter-scfg = "scm"
tree-sitter-scheme = "scm"
tree-sitter-scss = "scm"
tree-sitter-slang = "scm"
tree-sitter-slint = "scm"
tree-sitter-smali = "scm"
tree-sitter-smithy = "scm"
tree-sitter-snakemake = "scm"
tree-sitter-solidity = "scm"
tree-sitter-soql = "scm"
tree-sitter-sosl = "scm"
tree-sitter-sourcepawn = "scm"
tree-sitter-sparql = "scm"
tree-sitter-sql = "scm"
tree-sitter-squirrel = "scm"
tree-sitter-ssh_config = "scm"
tree-sitter-starlark = "scm"
tree-sitter-strace = "scm"
tree-sitter-styled = "scm"
tree-sitter-supercollider = "scm"
tree-sitter-surface = "scm"
tree-sitter-svelte = "scm"
tree-sitter-swift = "scm"
tree-sitter-sxhkdrc = "scm"
tree-sitter-systemtap = "scm"
tree-sitter-systemverilog = "scm"
tree-sitter-t32 = "scm"
tree-sitter-tablegen = "scm"
tree-sitter-tact = "scm"
tree-sitter-tcl = "scm"
tree-sitter-teal = "scm"
tree-sitter-templ = "scm"
tree-sitter-terraform = "scm"
tree-sitter-textproto = "scm"
tree-sitter-thrift = "scm"
tree-sitter-tiger = "scm"
tree-sitter-tlaplus = "scm"
tree-sitter-tmux = "scm"
tree-sitter-todotxt = "scm"
tree-sitter-toml = "scm"
tree-sitter-tsv = "scm"
tree-sitter-tsx = "scm"
tree-sitter-turtle = "scm"
tree-sitter-twig = "scm"
tree-sitter-typescript = "scm"
tree-sitter-typespec = "scm"
tree-sitter-typoscript = "scm"
tree-sitter-typst = "scm"
tree-sitter-udev = "scm"
tree-sitter-ungrammar = "scm"
tree-sitter-unison = "scm"
tree-sitter-usd = "scm"
tree-sitter-uxntal = "scm"
tree-sitter-v = "scm"
tree-sitter-vala = "scm"
tree-sitter-vento = "scm"
tree-sitter-verilog = "scm"
tree-sitter-vhdl = "scm"
tree-sitter-vhs = "scm"
tree-sitter-vim = "scm"
tree-sitter-vimdoc = "scm"
tree-sitter-vue = "scm"
tree-sitter-wgsl = "scm"
tree-sitter-wgsl_bevy = "scm"
tree-sitter-wing = "scm"
tree-sitter-wit = "scm"
tree-sitter-xcompose = "scm"
tree-sitter-xml = "scm"
tree-sitter-yaml = "scm"
tree-sitter-yang = "scm"
tree-sitter-yuck = "scm"
tree-sitter-zathurarc = "scm"
tree-sitter-zig = "scm"
