---
"on":
  push:
    paths-ignore:
      - "**.md"
  pull_request:
    paths-ignore:
      - "**.md"
  workflow_dispatch:

# https://github.com/softprops/action-gh-release/issues/236
permissions:
  contents: write

env:
  files: dist/*

# disable windows
# invalid path '.password-store/https:/test.pypi.org/legacy/__token__.gpg'
jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        runs-on:
          - ubuntu-latest
          - macos-latest
    runs-on: ${{matrix.runs-on}}
    steps:
      - uses: actions/checkout@v4
      - uses: astral-sh/setup-uv@v6
      - name: Build
        run: |
          uv build
      - uses: actions/upload-artifact@v4
        if: ${{! startsWith(github.ref, 'refs/tags/')}}
        with:
          name: artifact-${{matrix.runs-on}}
          path: |
            ${{env.files}}
      - uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            ${{env.files}}

  publish:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - uses: actions/checkout@v4
      - uses: docker/login-action@v3
        if: github.event_name != 'pull_request'
        with:
          username: ${{secrets.DOCKER_USERNAME}}
          password: ${{secrets.DOCKER_PASSWORD}}
      - uses: docker/login-action@v3
        if: github.event_name != 'pull_request'
        with:
          registry: ghcr.io
          username: ${{github.actor}}
          password: ${{secrets.GITHUB_TOKEN}}
      - id: meta
        uses: docker/metadata-action@v5
        with:
          images: |
            ${{secrets.DOCKER_USERNAME}}/freed-wu
            ghcr.io/${{github.repository}}
      - uses: docker/build-push-action@v6
        with:
          context: .
          push: ${{github.event_name != 'pull_request'}}
          tags: ${{steps.meta.outputs.tags}}
          labels: ${{steps.meta.outputs.labels}}
          file: script/Dockerfile
