---
"on":
  schedule:
    - cron: "40 1 * * *"
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: superman66/wakatime-sync@v1.0.0
        env:
          GH_TOKEN: ${{secrets.GH_TOKEN}}
          GIST_ID: ${{secrets.GIST_ID}}
          WAKATIME_API_KEY: ${{secrets.WAKATIME_API_KEY}}
          SCU_KEY: ${{secrets.SCU_KEY}}
